version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    # command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus-home.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
#  snmp:
#    image: prom/snmp-exporter
#    volumes:
#      - ./snmp-exporter:/etc/snmp_exporter
#    ports:
#      - 9116:9116
#      - 116:116/udp
#    restart: always
#    command: --config.file=/etc/snmp_exporter/snmp.yml

volumes:
  prometheus-data:
  grafana-data:
