global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: node_exporter
    static_configs:
      - targets: ["192.168.1.171:9100"]
  - job_name: windows_node
    static_configs:
      - targets: ["192.168.1.236:9182"]
#  - job_name: 'snmp'
#    static_configs:
#      - targets:
#        - 192.168.1.2  # SNMP device.
#    metrics_path: /snmp
#    params:
#      module: [if_mib]
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 192.168.1.171:9116  # The SNMP exporter's real hostname:port.
